name: Frontend Security Pipeline

on:
  workflow_dispatch: 

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    
    - name: Install Dependencies
      run: npm install
      
    - name: Build App
      run: npm run build
    
  sast:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Horusec (SAST)
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/src \
        horuszup/horusec-cli:latest horusec start \
          -p /src \
          -D \
          -s="LOW,MEDIUM" \
          -e